services:
  app:
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=your_project.settings.prod
    ports:
      - "80:8000"
    command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRES_DB=${POSTGRES_DB_PROD}
      - POSTGRES_USER=${POSTGRES_USER_PROD}
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL_PROD}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD_PROD}
    ports:
      - 5050:80
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
