name: Build Docker Image

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEBUG: "True"
      #DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t redjango_app .
          docker tag redjango_app guifernandess7/redjango_app:latest
          docker push guifernandess7/redjango_app:latest
