name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: build

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: test
    if: github.ref == 'refs/heads/main'
