name: Deploy Application

on:
  push:
    branches:
      #- dev
      - main

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy to Staging Server
        run: |
          ssh user@staging-server "docker pull GuiFernandess7/redjango:latest && docker-compose up -d"

  deploy_production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy to Production Server
        run: |
          ssh user@production-server "docker pull GuiFernandess7/redjango:latest && docker-compose up -d"
